/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package videostoretest;

import javax.swing.*;
import java.io.*;
import java.net.*;
import java.util.regex.*;
import java.sql.*;

/**
 *
 * @author DJ
 */
public class AdminGui extends javax.swing.JFrame {

    /**
     * Creates new form AdminGui
     */
    public AdminGui() {
        initComponents();
        setTitle("Administrator");
    }
    
    Socket userSocket = null;
    PrintWriter out = null;
    BufferedReader in = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        UserNameTextField = new javax.swing.JTextField();
        LogInButton = new javax.swing.JButton();
        MoviePasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MovieTitleATextField = new javax.swing.JTextField();
        MovieGenreTextField = new javax.swing.JTextField();
        MovieDescTextField = new javax.swing.JTextField();
        MovieAddButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        GenreAddButton = new javax.swing.JButton();
        GenreNameTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        MovieTitleRTextField = new javax.swing.JTextField();
        MovieTitleRemoveButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ClientMenuItem = new javax.swing.JMenuItem();
        AdminMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        HelpMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminTabbedPane.setName(""); // NOI18N

        UserNameTextField.setText("User Name");
        UserNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextFieldActionPerformed(evt);
            }
        });

        LogInButton.setText("Log in");
        LogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInButtonActionPerformed(evt);
            }
        });

        PasswordLabel.setText("Password :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PasswordLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(UserNameTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addComponent(LogInButton))
                    .addComponent(MoviePasswordField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(UserNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoviePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogInButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdminTabbedPane.addTab("Login", jPanel1);

        MovieTitleATextField.setText("Movie Title");
        MovieTitleATextField.setEnabled(false);
        MovieTitleATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieTitleATextFieldActionPerformed(evt);
            }
        });

        MovieGenreTextField.setText("Movie genre");
        MovieGenreTextField.setEnabled(false);

        MovieDescTextField.setText("Movie Description");
        MovieDescTextField.setEnabled(false);

        MovieAddButton.setText("Add");
        MovieAddButton.setEnabled(false);
        MovieAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MovieAddButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MovieDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MovieGenreTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(MovieTitleATextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MovieTitleATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MovieGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MovieDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MovieAddButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        AdminTabbedPane.addTab("Add Movie", jPanel2);

        GenreAddButton.setText("Add");
        GenreAddButton.setEnabled(false);
        GenreAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreAddButtonActionPerformed(evt);
            }
        });

        GenreNameTextField.setText("Genre Name");
        GenreNameTextField.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GenreNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GenreAddButton)))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(GenreNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(GenreAddButton)
                .addGap(45, 45, 45))
        );

        AdminTabbedPane.addTab("Add Genre", jPanel3);

        MovieTitleRTextField.setText("Movie Title");
        MovieTitleRTextField.setEnabled(false);

        MovieTitleRemoveButton.setText("Remove");
        MovieTitleRemoveButton.setEnabled(false);
        MovieTitleRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieTitleRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(MovieTitleRTextField)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(MovieTitleRemoveButton)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(MovieTitleRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MovieTitleRemoveButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        AdminTabbedPane.addTab("Remove Title", jPanel4);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        ClientMenuItem.setText("Client View");
        jMenu1.add(ClientMenuItem);

        AdminMenuItem.setText("Admin View");
        AdminMenuItem.setEnabled(false);
        jMenu1.add(AdminMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        HelpMenuItem.setText("Show Help");
        HelpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(HelpMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovieTitleATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieTitleATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MovieTitleATextFieldActionPerformed

    private void UserNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextFieldActionPerformed

    private void MovieAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieAddButtonActionPerformed
        boolean startCapital;
        String updateDB;
        boolean isWordName = true;
        boolean isWordDesc = true;
        String movieName = MovieTitleATextField.getText();
        String movieGenre = MovieGenreTextField.getText();
        String movieDesc = MovieGenreTextField.getText();

        isWordName = Pattern.compile("[A-Z].*").matcher(movieName).matches();
        isWordDesc = Pattern.compile("[A-A].*").matcher(movieDesc).matches();

        if (isWordDesc && isWordName) {
            out.println("3!" + movieName + "!" + movieGenre + "!" + movieDesc);

            try {
                updateDB = in.readLine();

                startCapital = Pattern.compile("[A-Z].*").matcher(movieName).matches();
                if (!startCapital) {
                    JOptionPane.showMessageDialog(null, "Movie must start with a capital letter.", "Error", 0);
                }

                if (updateDB.equals("0")) {
                    JOptionPane.showMessageDialog(null, "The movie has been successfully added.", "Message", 1);
                } else if (updateDB.equals("1")) {
                    JOptionPane.showMessageDialog(null, "The movie already exists", "Message", 0);
                } else {
                    JOptionPane.showMessageDialog(null, "The genre does not exist.", "message", 0);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e, "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Genre or Description field left blank", "Message", 0);
        }
    }//GEN-LAST:event_MovieAddButtonActionPerformed

    private void LogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInButtonActionPerformed
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Connection con = DriverManager.getConnection("jdbc:odbc:VideoStore", "", "");
            Statement stat = con.createStatement();
            String query = new String(MoviePasswordField.getPassword());
            ResultSet results = stat.executeQuery("SELECT * FROM Users "
                                                + "WHERE user_name = '" + UserNameTextField.getText() + "' AND password = '"
                                                + query + "'");
            if (!results.next()) {
                throw new InvalidPasswordException();
            } else {
                JOptionPane.showMessageDialog(null, "You are successfully logon", "Logon Status", 1);
                MovieTitleATextField.setEnabled(true);
                MovieGenreTextField.setEnabled(true);
                MovieDescTextField.setEnabled(true);
                MovieAddButton.setEnabled(true);
                GenreNameTextField.setEnabled(true);
                GenreAddButton.setEnabled(true);
                MovieTitleRTextField.setEnabled(true);
                MovieTitleRemoveButton.setEnabled(true);
                LogInButton.setEnabled(false);
                try {
                    userSocket = new Socket("127.0.0.1", 6666);
                    out = new PrintWriter(userSocket.getOutputStream(), true);
                    in = new BufferedReader(new InputStreamReader(userSocket.getInputStream()));
                } catch (UnknownHostException e) {
                    JOptionPane.showMessageDialog(null, e, "Error Message", 0);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, e, "Error Message", 0);
                }
            }
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error Message", 0);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e, "Error Message", 0);
        } catch (InvalidPasswordException e) {
            JOptionPane.showMessageDialog(null, e, "Error Message", 0);
        }
    }//GEN-LAST:event_LogInButtonActionPerformed

    private void GenreAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreAddButtonActionPerformed
        String movGenre = GenreNameTextField.getText();
        boolean isWord = true;
                System.out.println("1");
        
        isWord = Pattern.compile("[A-Z].*").matcher(movGenre).matches();
        
        if (isWord) {
                System.out.println("2");
            out.println("5!" + movGenre);
                System.out.println("3");
            try {
                String addNewGenre = in.readLine();
                System.out.println("4");
                if (addNewGenre.equals("0")) {
                    JOptionPane.showMessageDialog(null, "The genre already exists!!", "Error", 0);
                } else {
                    JOptionPane.showMessageDialog(null, "New genre added successfully!!", "Genre Added!!", 1);
                }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, e, "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "The text fiels has no input \nor the genre name does not start with a capital letter!!", "Error", 0);
        }
    }//GEN-LAST:event_GenreAddButtonActionPerformed

    private void MovieTitleRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieTitleRemoveButtonActionPerformed
        String delMovie = MovieTitleRTextField.getText();
        out.println("4!" + delMovie);
        try {
            String delRecord = in.readLine();
            if (delRecord.equals("0")) {
                JOptionPane.showMessageDialog(null, "The movie has been successfully deleted!!!", "Videio Deleted", 1);
            } else {
                JOptionPane.showMessageDialog(null, "the movie does not exist!!", "Error", 0);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e, "Error", 0);
        }
    }//GEN-LAST:event_MovieTitleRemoveButtonActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        MovieTitleATextField.setEnabled(false);
        MovieGenreTextField.setEnabled(false);
        MovieDescTextField.setEnabled(false);
        MovieAddButton.setEnabled(false);
        GenreNameTextField.setEnabled(false);
        GenreAddButton.setEnabled(false);
        MovieTitleRTextField.setEnabled(false);
        MovieTitleRemoveButton.setEnabled(false);
        LogInButton.setEnabled(true);
        new UserGui().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void HelpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuItemActionPerformed
        new HelpGui().setVisible(true);
    }//GEN-LAST:event_HelpMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdminMenuItem;
    private javax.swing.JTabbedPane AdminTabbedPane;
    private javax.swing.JMenuItem ClientMenuItem;
    private javax.swing.JButton GenreAddButton;
    private javax.swing.JTextField GenreNameTextField;
    private javax.swing.JMenuItem HelpMenuItem;
    private javax.swing.JButton LogInButton;
    private javax.swing.JButton MovieAddButton;
    private javax.swing.JTextField MovieDescTextField;
    private javax.swing.JTextField MovieGenreTextField;
    private javax.swing.JPasswordField MoviePasswordField;
    private javax.swing.JTextField MovieTitleATextField;
    private javax.swing.JTextField MovieTitleRTextField;
    private javax.swing.JButton MovieTitleRemoveButton;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UserNameTextField;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    private static class InvalidPasswordException  extends Exception{}
}
